#!/bin/bash
bash scripts/final_1_scripts/chap5/quantized_inference_pi/8w8a/myfyp_frompretrainedmodel_prompttuning_lora_single_mitbih.sh
bash scripts/final_1_scripts/chap5/quantized_inference_pi/8w8a/myfyp_frompretrainedmodel_prompttuning_single_mitbih.sh
bash scripts/final_1_scripts/chap5/quantized_inference_pi/8w8a/myfyp_frompretrainedmodel_prompttuning_lora_single_ucihar.sh
bash scripts/final_1_scripts/chap5/quantized_inference_pi/8w8a/myfyp_frompretrainedmodel_prompttuning_single_ucihar.sh
bash scripts/final_1_scripts/chap5/quantized_inference_pi/8w8a/myfyp_frompretrainedmodel_prompttuning_lora_single_wesad.sh
bash scripts/final_1_scripts/chap5/quantized_inference_pi/8w8a/myfyp_frompretrainedmodel_prompttuning_single_wesad.sh